version: '3'
services:
  faust:
    tty: true
    build: ./faust_app
    container_name: faust
    depends_on:
      - zookeeper
      - kafka
    environment:
      - WORKER=app
      - WORKER_PORT=6066
      - KAFKA_BOOTSTRAP_SERVER=kafka://kafka:9092
      - KAFKA_BOOSTRAP_SERVER_NAME=kafka
      - KAFKA_BOOSTRAP_SERVER_PORT=9092
    ports:
      - "8084:80"
      - "8000:8000"
      - "6066:6066"
      - "50101:50101"
    volumes:
      - ./scripts:/faust/scripts
  zookeeper:
    image: "confluentinc/cp-zookeeper"
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 32181:32181
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    ports:
    - 9092:9092
    - 29092:29092
    depends_on:
    - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:29092,PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1

